on:
  push:

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: ls fun
        working-directory: lsfun
        run: |
          bash summary.sh
          echo "EE?"
          bash summary.sh >> SGITHUB_STEP_SUMMARY
