name: Bash examples
run-name: Run bash examples ${{github.sha}}
on:
  push:

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: ls fun
        run: |
          make lsfun >> $GITHUB_STEP_SUMMARY
      - name: input arguments
        run: |
          make basharguments >> $GITHUB_STEP_SUMMARY
