name: Bash examples
run-name: Run bash examples ${{github.ref}}
on:
  push:

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: ls fun
        working-directory: lsfun
        run: |
          bash summary.sh >> $GITHUB_STEP_SUMMARY
